### ISSUE TITLE
Name of site too small in top nav for reading!

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/sustain#55]
![screen shot 2016-06-09 at 9 07 35 am](https://cloud.githubusercontent.com/assets/10924897/15930608/d68b0156-2e21-11e6-9f16-ebb5754a7937.png)

Name of site too small in top nav for reading!

Also- I believe Sustain uses the font 'creamy' in their branding as their tagline, but it's an image as that font isn't available online. The closest web font to that looks like lobster: https://typekit.com/fonts/lobster
Should we give this one a ago instead? It might have better legibility.

![screen shot 2016-06-09 at 9 10 15 am](https://cloud.githubusercontent.com/assets/10924897/15930853/09f36be0-2e23-11e6-9e31-a3db7557fd72.png)

**Comment by emdecr** [comment]
True! I changed it to lobster and increase the size. Thoughts?

**Comment by jenphelan** [comment]
yes i think it's better! :)
